services:
  - type: static
    name: flexoapp-frontend
    buildCommand: npm ci --include=dev && npx ng build --configuration=render
    publishDir: dist/browser
    envVars:
      - key: NODE_ENV
        value: production
      - key: ANGULAR_ENV
        value: render
      - key: API_URL
        value: https://flexoapp-backend.onrender.com/api