// <auto-generated />
using System;
using FlexoAPP.API.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlexoAPP.API.Migrations
{
    [DbContext(typeof(FlexoAPPDbContext))]
    [Migration("20251009171728_SyncDesignsTable")]
    partial class SyncDesignsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FlexoAPP.API.Models.Entities.Design", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ArticleF")
                        .HasColumnType("longtext");

                    b.Property<string>("Client")
                        .HasColumnType("longtext");

                    b.Property<string>("Color1")
                        .HasColumnType("longtext")
                        .HasColumnName("color 1");

                    b.Property<string>("Color10")
                        .HasColumnType("longtext")
                        .HasColumnName("color 10");

                    b.Property<string>("Color2")
                        .HasColumnType("longtext")
                        .HasColumnName("color 2");

                    b.Property<string>("Color3")
                        .HasColumnType("longtext")
                        .HasColumnName("color 3");

                    b.Property<string>("Color4")
                        .HasColumnType("longtext")
                        .HasColumnName("color 4");

                    b.Property<string>("Color5")
                        .HasColumnType("longtext")
                        .HasColumnName("color 5");

                    b.Property<string>("Color6")
                        .HasColumnType("longtext")
                        .HasColumnName("color 6");

                    b.Property<string>("Color7")
                        .HasColumnType("longtext")
                        .HasColumnName("color 7");

                    b.Property<string>("Color8")
                        .HasColumnType("longtext")
                        .HasColumnName("color 8");

                    b.Property<string>("Color9")
                        .HasColumnType("longtext")
                        .HasColumnName("color 9");

                    b.Property<int?>("ColorCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Designer")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PrintType")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Substrate")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("designs", (string)null);
                });

            modelBuilder.Entity("FlexoAPP.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Area")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Permissions")
                        .HasColumnType("JSON");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("LONGTEXT");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Role");

                    b.HasIndex("UserCode")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
